version: '3.8'

services:
  web:
    build: .
    container_name: django_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: faf
      DB_USER: fafuser
      DB_PASSWORD: FQ^2t73Ava
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: faf
      MYSQL_USER: fafuser
      MYSQL_PASSWORD: FQ^2t73Ava
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
